function Kuntaliittokooditjakestot2022TODELLISETAJATS3 = importTutkimuskestot(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  KUNTALIITTOKOODITJAKESTOT2022TODELLISETAJATS3 = IMPORTFILE1(FILE)
%  reads data from the first worksheet in the Microsoft Excel
%  spreadsheet file named FILE.  Returns the data as a table.
%
%  KUNTALIITTOKOODITJAKESTOT2022TODELLISETAJATS3 = IMPORTFILE1(FILE,
%  SHEET) reads from the specified worksheet.
%
%  KUNTALIITTOKOODITJAKESTOT2022TODELLISETAJATS3 = IMPORTFILE1(FILE,
%  SHEET, DATALINES) reads from the specified worksheet for the
%  specified row interval(s). Specify DATALINES as a positive scalar
%  integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  Kuntaliittokooditjakestot2022TODELLISETAJATS3 = importfile1("/Users/mikaeljuntunen/Documents_Mikael/Studies/KTM/Masters thesis/DATA/Kuntaliittokoodit_ja_kestot_2022_TODELLISET_AJAT.xlsx", "Tutkimuskooditilastot", [1, 179]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Dec-2023 16:17:10

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, 159];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":G" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["CPTCode", "TutkimuksenNimi", "KuvaustenLkm", "Keskiarvo", "Keskihajonta", "Mediaani", "Keskihajontakeskiarvo"];
opts.VariableTypes = ["string", "string", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["CPTCode", "TutkimuksenNimi"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["CPTCode", "TutkimuksenNimi"], "EmptyFieldRule", "auto");

% Import the data
Kuntaliittokooditjakestot2022TODELLISETAJATS3 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":G" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Kuntaliittokooditjakestot2022TODELLISETAJATS3 = [Kuntaliittokooditjakestot2022TODELLISETAJATS3; tb]; %#ok<AGROW>
end

end