function Kuntaliittokooditjakestot2022TODELLISETAJAT = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  KUNTALIITTOKOODITJAKESTOT2022TODELLISETAJAT = IMPORTFILE1(FILE) reads
%  data from the first worksheet in the Microsoft Excel spreadsheet file
%  named FILE.  Returns the data as a table.
%
%  KUNTALIITTOKOODITJAKESTOT2022TODELLISETAJAT = IMPORTFILE1(FILE,
%  SHEET) reads from the specified worksheet.
%
%  KUNTALIITTOKOODITJAKESTOT2022TODELLISETAJAT = IMPORTFILE1(FILE,
%  SHEET, DATALINES) reads from the specified worksheet for the
%  specified row interval(s). Specify DATALINES as a positive scalar
%  integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  Kuntaliittokooditjakestot2022TODELLISETAJAT = importfile1("/Users/mikaeljuntunen/Documents_Mikael/Studies/KTM/Masters thesis/DATA/Kuntaliittokoodit_ja_kestot_2022_TODELLISET_AJAT.xlsx", "Data", [2, 21569]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Dec-2023 19:39:18

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 21569];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "C" + dataLines(1, 1) + ":F" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["HuoneMRIlaite", "Kiireellisyysluokka", "Tutkimuskoodi", "Kuvausaika"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "double"];

% Specify variable properties
opts = setvaropts(opts, ["HuoneMRIlaite", "Kiireellisyysluokka", "Tutkimuskoodi"], "EmptyFieldRule", "auto");

% Import the data
Kuntaliittokooditjakestot2022TODELLISETAJAT = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "C" + dataLines(idx, 1) + ":F" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Kuntaliittokooditjakestot2022TODELLISETAJAT = [Kuntaliittokooditjakestot2022TODELLISETAJAT; tb]; %#ok<AGROW>
end

end